const types = {
  OUTLET_FETCH_REQUESTED: "COFFEE/OUTLET_FETCH_REQUESTED",
  OUTLET_FETCH_SUCCEEDED: "COFEE/OUTLET_FETCH_SUCCEEDED",
  OUTLET_FETCH_FAILED: "COFEE/OUTLET_FETCH_FAILED"
};
export default types;
